USE DESAFIO;

CREATE TABLE FORNECEDORES(
    ID LONG,
    NAME    	VARCHAR(60) ,
    DATE_OF_CREATION      TIMESTAMP ,
    DATE_OF_THE_LAST_UPDATE	TIMESTAMP
);


INSERT INTO FORNECEDORES VALUES (1,'JOÃO DA SILVA', now(), NULL);
INSERT INTO FORNECEDORES VALUES (2,'FERNANDO CARDOSO', NOW(), NULL);
INSERT INTO FORNECEDORES VALUES (3,'GUSTAVO SANTOS', NOW() , NULL);