USE DESAFIO;

CREATE TABLE FORNECEDORES(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME    	VARCHAR(60) NOT NULL ,
    DATE_OF_CREATION      TIMESTAMP NOT NULL ,
    DATE_OF_THE_LAST_UPDATE	TIMESTAMP,
	PRIMARY KEY (ID)
);

INSERT INTO FORNECEDORES VALUES (1,'CARREFOUR COMERCIO E INDUSTRIA LTDA', now(), NULL);
INSERT INTO FORNECEDORES VALUES (2,'COMPANHIA BRASILEIRA DE DISTRIBUIÇÃO (GRUPO PÃO DE AÇUCAR)', NOW(), NULL);
INSERT INTO FORNECEDORES VALUES (3,'SUPERMERCADOS MAMBO LTDA', NOW() , NULL);

CREATE TABLE PRODUTOS(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME    	VARCHAR(60) ,
    QUANTITY_IN_STOCK LONG,
    UNIT_PRICE DOUBLE,
    SUPPLIER_ID INT,
    DATE_OF_CREATION      TIMESTAMP ,
    DATE_OF_THE_LAST_UPDATE	TIMESTAMP,
	PRIMARY KEY (ID),
    CONSTRAINT FK_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES FORNECEDORES (ID)
);
